project:
  type: book
  output-dir: docs

book:
  title: "Programación práctica con R"
  reader-mode: true
  
  page-footer:
    left: |
      Programación práctica con R fue escrito por Garrett Grolemund.
    right: |
      Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: projectlogo.png
  author: 
    - name: Garrett Grolemund
  search: true
  sidebar: 
    pinned: true
    tools: 
      - icon: github
        menu: 
          - text: Original
            url: https://github.com/rstudio-education/hopr
          - text: Traducción
            url: https://github.com/davidrsch/hopres
  chapters:
    - index.qmd
    - preface.qmd
    - part: dice.qmd
      chapters:
        - basics.qmd
        - packages.qmd
    - part: cards.qmd
      chapters:
        - objects.qmd
        - notation.qmd
        - modifying.qmd
        - environments.qmd
    - part: slots.qmd
      chapters:
        - programs.qmd
        - s3.qmd
        - loops.qmd
        - speed.qmd
  appendices: 
    - a1-starting.qmd
    - a2-packages.qmd
    - a3-updating.qmd
    - a4-data.qmd
    - a5-debug.qmd
lang: es


format:
  html:
    theme:
      - cosmo
      - hopr.scss
    code-link: true
    author-meta: "Garrett Grolemund"
    callout-appearance: simple
    include-in-header: [ddrsch_script_header.html]
    include-after-body: [ddrsch_script.html]

editor: visual

