# Paquetes de R {#packages2}

Muchas de las funciones más útiles de R no vienen precargadas cuando inicia R, sino que residen en _paquetes_ que se pueden instalar encima de R. Los paquetes de R son similares a las bibliotecas en C, C++ y Javascript, los paquetes en Python y las gemas en Ruby. Un paquete de R agrupa funciones útiles, archivos de ayuda y conjuntos de datos. Puede usar estas funciones dentro de su propio código de R una vez que cargue el paquete en el que se encuentran. Por lo general, el contenido de un paquete de R está relacionado con un solo tipo de tarea, que el paquete ayuda a resolver. Los paquetes R le permitirán aprovechar las características más útiles de R: su gran comunidad de creadores de paquetes (muchos de los cuales son científicos de datos activos) y sus rutinas preescritas para manejar muchas tareas comunes (y exóticas) de ciencia de datos.

```{block2, type = "rmdtip"}
**R Básico**
  
Es posible que escuche a los usuarios de R (o a mí) referirse a "R básico" (o base R, en inglés). ¿Qué es R básico? Es solo la colección de funciones de R que se carga cada vez que inicia R. Estas funciones proporcionan los conceptos básicos del lenguaje, y no tiene que cargar un paquete antes de poder usarlas..
```

## Instalando Paquetes

Para usar un paquete de R, primero debe instalarlo en su computadora y luego cargarlo en su sesión de R actual. La forma más fácil de instalar un paquete de R es con la función de R `install.packages`. Abra R y escriba lo siguiente en la línea de comando:  

```r
install.packages("<nombre del paquete>")
```

Esto buscará el paquete especificado en la colección de paquetes alojados en el sitio CRAN. Cuando R encuentre el paquete, lo descargará en una carpeta de bibliotecas en su computadora. R puede acceder al paquete aquí en futuras sesiones de R sin reinstalarlo. Cualquiera puede escribir un paquete R y distribuirlo como quiera; sin embargo, casi todos los paquetes de R se publican a través del sitio web de CRAN. CRAN prueba cada paquete R antes de publicarlo. Esto no elimina todos los errores dentro de un paquete, pero significa que puede confiar en que un paquete en CRAN se ejecutará en la versión actual de R en su sistema operativo.

Puede instalar varios paquetes a la vez vinculando sus nombres con la función de concatenación de R, `c`. Por ejemplo, para instalar los paquetes ggplot2, reshape2 y dplyr, ejecute:

```r
install.packages(c("ggplot2", "reshape2", "dplyr"))
```

Si es la primera vez que instala un paquete, R le pedirá que elija un espejo en línea para instalarlo. Los espejos se enumeran por ubicación. Sus descargas deberían ser más rápidas si selecciona un espejo que esté cerca de usted. Si desea descargar un nuevo paquete, pruebe primero el espejo de Austria. Este es el repositorio principal de CRAN y, a veces, los nuevos paquetes pueden tardar un par de días en llegar a todos los demás espejos. 

## Cargando Paquetes

La instalación de un paquete no pone inmediatamente sus funciones al alcance de su mano. Simplemente los coloca en su computadora. Para usar un paquete de R, luego debe cargarlo en su sesión de R con el comando:

```r
library(<nombre del paquete>)
```

Observe que las comillas han desaparecido. Puede usarlos si lo desea, pero las comillas son opcionales para el comando `library`. (Esto no es cierto para el comando `install.packages`).

`library` pondrá a su disposición todas las funciones, conjuntos de datos y archivos de ayuda del paquete hasta que cierre su sesión de R actual. La próxima vez que inicie una sesión de R, deberá volver a cargar el paquete con `library` si desea utilizarlo, pero no tendrá que volver a instalarlo. Solo tiene que instalar cada paquete una vez. Después de eso, una copia del paquete vivirá en su biblioteca de R. Para ver qué paquetes tiene actualmente en su biblioteca de R, ejecute:

```r
library()
```

`library()` también muestra la ruta a su biblioteca de R actual, que es la carpeta que contiene sus paquetes de R. Puede notar muchos paquetes que no recuerda haber instalado. Esto se debe a que R descarga automáticamente un conjunto de paquetes útiles cuando instala R por primera vez.

```{block2, type = "rmdtip"}
**Instalar paquetes desde (casi) cualquier sitio**
  
El paquete `devtools` de R facilita la instalación de paquetes desde ubicaciones distintas al sitio web de CRAN. devtools proporciona funciones como `install_github`, `install_gitorious`, `install_bitbucket` e `install_url`. Estos funcionan de manera similar a `install.packages`, pero buscan nuevas ubicaciones para paquetes de R. `install_github` es especialmente útil porque muchos desarrolladores de R proporcionan versiones de desarrollo de sus paquetes en GitHub. La versión de desarrollo de un paquete contendrá un adelanto de nuevas funciones y parches, pero puede que no sea tan estable o libre de errores como la versión CRAN.
```

¿Por qué R hace que te molestes en instalar y cargar paquetes? Puede imaginar una versión de R en la que todos los paquetes vengan precargados, pero este sería un programa muy grande y lento. A fecha del 6 de mayo de 2014, el sitio web de CRAN albergaba 5511 paquetes. Es más simple instalar y cargar solo los paquetes que desea usar cuando desea usarlos. Esto mantiene su copia de R rápida porque tiene menos funciones y páginas de ayuda para buscar en cualquier momento. Esto también tiene otros beneficios, por ejemplo, es posible actualizar su copia de un paquete de R sin actualizar toda su copia de R.


```{block2, type = "rmdtip"}
**¿Cuál es la mejor manera de aprender sobre los paquetes de R?**

Es difícil usar un paquete de R si no sabe que existe. Puede ir al sitio web de CRAN y hacer clic en el enlace Paquetes para ver una lista de paquetes disponibles, pero tendrá que leer miles de ellos. Además, muchos paquetes de R hacen lo mismo. 

¿Cómo sabe qué paquete los hace mejor? Los paquetes de R [lista de correo](http://stat.ethz.ch/mailman/listinfo/r-packages) es un lugar para comenzar. Envía anuncios de nuevos paquetes y mantiene un archivo de anuncios antiguos.Los blogs que agregan publicaciones sobre R también pueden proporcionar pistas valiosas, recomiendo [R-bloggers](www.r-bloggers.com). Posit mantiene una lista de algunos de los paquetes R más útiles en la sección de Getting Started de [https://support.posit.co/](https://support.posit.co/). Finalmente, CRAN agrupa algunos de los paquetes más útiles y más respetados por [área temática](http://cran.r-project.org/web/views). Este es un excelente lugar para conocer los paquetes diseñados para su área de trabajo.
```
