# Actualizando R y sus Paquetes {#updating}

El equipo de desarrollo de R Core perfecciona continuamente el lenguaje R detectando errores, mejorando el rendimiento y actualizando R para que funcione con nuevas tecnologías. Como resultado, se lanzan nuevas versiones de R varias veces al año. La forma más fácil de mantenerse actualizado con R es consultar periódicamente [el sitio web de CRAN](http://cran.r-project.org). El sitio web se actualiza para cada nueva versión y hace que la versión esté disponible para su descarga. Tendrás que instalar la nueva versión. El proceso es el mismo que cuando instaló R por primera vez.

No se preocupe si no está interesado en mantenerse actualizado sobre las actividades de R Core. R cambia solo ligeramente entre versiones, y es probable que no note las diferencias. Sin embargo, actualizar a la versión actual de R es un buen lugar para comenzar si alguna vez encuentra un error que no puede explicar. 

Posit también mejora constantemente su producto, RStudio. Puede adquirir las actualizaciones más recientes simplemente descargándolas de [Posit](https://posit.co/download/rstudio-desktop).

## Paquetes de R

Los autores de paquetes ocasionalmente lanzan nuevas versiones de sus paquetes para agregar funciones, corregir errores o mejorar el rendimiento. El comando `update.packages` verifica si tiene la versión más actual de un paquete e instala la versión más actual si no la tiene. La sintaxis de `update.packages` sigue la de `install.packages`. Si ya tiene ggplot2, reshape2 y dplyr en su computadora, sería una buena idea buscar actualizaciones antes de usarlas:

```r
update.packages(c("ggplot2", "reshape2", "dplyr"))
```

Debe iniciar una nueva sesión de R después de actualizar los paquetes. Si tiene un paquete cargado cuando lo actualiza, deberá cerrar su sesión de R y abrir una nueva para comenzar a usar la versión actualizada del paquete.
